# Generated by Django 3.2.4 on 2021-07-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                
                ('phone', models.CharField(max_length=10)),
                
                ('college', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=1)),
                ('stream', models.CharField(max_length=60)),
                ('domain', models.CharField(max_length=60)),
                
                ('teamnum', models.CharField(max_length=1)),
                ('teamname', models.CharField(max_length=50)),
                ('teammemname1', models.CharField(max_length=100)),
                ('teammememail1', models.EmailField(max_length=100)),
                ('teammemname2', models.CharField(max_length=100)),
                ('teammememail2', models.EmailField(max_length=100)),
                ('teammemname3', models.CharField(max_length=100)),
                ('teammememail3', models.EmailField(max_length=100)),
                ('teammemname4', models.CharField(max_length=100)),
                ('teammememail4', models.EmailField(max_length=100)),
            ],
        ),
    ]
