# Generated by Django 3.2.4 on 2021-07-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackxsps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='college',
            new_name='Scollege',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='domain',
            new_name='Sdomain',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='Semail',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='firstname',
            new_name='Sfirstname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lastname',
            new_name='Slastname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phone',
            new_name='Sphone',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='stream',
            new_name='Sstream',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammememail1',
            new_name='Steammememail1',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammememail2',
            new_name='Steammememail2',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammememail3',
            new_name='Steammememail3',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammememail4',
            new_name='Steammememail4',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammemname1',
            new_name='Steammemname1',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammemname2',
            new_name='Steammemname2',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammemname3',
            new_name='Steammemname3',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teammemname4',
            new_name='Steammemname4',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teamname',
            new_name='Steamname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='teamnum',
            new_name='Steamnum',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='year',
            new_name='Syear',
        ),
    ]
