# Generated by Django 3.2.4 on 2021-07-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackxsps', '0002_auto_20210718_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Scollege',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Sdomain',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Semail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Sfirstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Slastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Sphone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Sstream',
            new_name='stream',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammememail1',
            new_name='teammememail1',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammememail2',
            new_name='teammememail2',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammememail3',
            new_name='teammememail3',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammememail4',
            new_name='teammememail4',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammemname1',
            new_name='teammemname1',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammemname2',
            new_name='teammemname2',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammemname3',
            new_name='teammemname3',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steammemname4',
            new_name='teammemname4',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steamname',
            new_name='teamname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Steamnum',
            new_name='teamnum',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Syear',
            new_name='year',
        ),
    ]
